apiVersion: v1
kind: Service
metadata: { name: visitas-api, namespace: visitas }
spec:
  type: ClusterIP
  selector: { app.kubernetes.io/name: visitas-api }
  ports: [{ name: http, port: 80, targetPort: 3001 }]
